-- Add voice config fields to Project
ALTER TABLE "Project" ADD COLUMN IF NOT EXISTS "voiceProvider" TEXT NOT NULL DEFAULT 'elevenlabs';
ALTER TABLE "Project" ADD COLUMN IF NOT EXISTS "voiceId" TEXT;
ALTER TABLE "Project" ADD COLUMN IF NOT EXISTS "voiceSpeed" DOUBLE PRECISION NOT NULL DEFAULT 1.0;
ALTER TABLE "Project" ADD COLUMN IF NOT EXISTS "voiceEmotion" TEXT NOT NULL DEFAULT 'neutral';
ALTER TABLE "Project" ADD COLUMN IF NOT EXISTS "burnSubtitles" BOOLEAN NOT NULL DEFAULT false;
