ALTER TABLE "ApiKey" ADD COLUMN IF NOT EXISTS "lastTestedAt"    TIMESTAMP(3);
ALTER TABLE "ApiKey" ADD COLUMN IF NOT EXISTS "lastTestStatus"  TEXT;
ALTER TABLE "ApiKey" ADD COLUMN IF NOT EXISTS "lastTestError"   TEXT;
ALTER TABLE "ApiKey" ADD COLUMN IF NOT EXISTS "lastTestLatency" INTEGER;
